import { chromium, devices } from "playwright";
const base = "http://127.0.0.1:5000";
const THEO = "48a416e1-4b4e-45f7-8a1e-7c8524b42c0e";
const b = await chromium.launch();
const p = await (await b.newContext({ ...devices["iPhone 14 Pro"] })).newPage();
await p.addInitScript(() => sessionStorage.setItem("kora-launched", "1"));
await p.goto(base + "/login", { waitUntil: "domcontentloaded" });
await p.getByTestId("input-login-email").waitFor({ state: "visible", timeout: 45000 });
await p.getByTestId("input-login-email").fill("elena@riverafamily.com");
await p.getByTestId("input-login-password").fill("riverafamily");
await p.getByTestId("button-login").click();
await p.waitForURL(/fund=|dashboard/i, { timeout: 30000 }).catch(() => {});
await p.waitForTimeout(2000);
const rows = await p.evaluate(async (id) => {
  const r = await fetch(`/api/funds/${id}/parent-contributions`, { credentials: "include" });
  const j = await r.json();
  return (Array.isArray(j) ? j : []).map(c => ({ amount: c.amount, frequency: c.frequency, status: c.status }));
}, THEO);
console.log("parent-contributions for Theo:", JSON.stringify(rows));
await b.close();
