// Action-item architecture — the "read vs resolved" split.
//
// The activities ledger is append-only and tracks every event that ever
// happened. Some of those events are informational ("Aunt May sent a
// memory note") — read = seen = resolved. Others are open todos
// ("Identity details need attention") — read != fixed. The parent might
// have seen the card and not fixed the actual problem yet; the bell
// badge clearing on visit was a small lie.
//
// This registry defines which event types are TODOS. For each todo
// type, the server derives whether it's currently resolved from the
// user/fund state — if KYC is now approved, the kyc_action_required
// todo is resolved even though the original activity row still exists
// in the ledger. The badge + UI counts reflect "still open" not "not
// yet seen."
//
// Snooze:
//   `funds.dismissedNudges` (existing JSONB column) is the snooze
//   store. Format: { [actionType]: ISO timestamp until }. When now >
//   stored timestamp, the todo re-surfaces. Default snooze = 24h.

export type ActionItemType =
  // User-identity / KYC. Generated server-side when KYC fails or stalls.
  | "kyc_action_required"
  | "kyc_pending_review"
  // Subscription billing failure. Generated by Stripe webhook.
  | "payment_failed"
  // Large-gift hold awaiting parent decision (approve / reject).
  | "large_gift_hold_started"
  // Derived from current fund/user state, NOT from an activity row:
  | "ssn_missing"              // fund.recipient_ssn_full_encrypted IS NULL → blocks investing
  | "activate_investing"       // fund.status !== 'active' (but everything else complete)
  | "recipient_details_missing"// UTMA fund without recipientFirstName + birthdate
  | "bank_not_linked"          // user has no bank account on file
  | "profile_incomplete";      // user missing firstName

export type ActionItemCategory = "identity" | "payment" | "fund_setup" | "gift_hold";

export interface ActionItem {
  // Stable key used for snooze + dedupe. Format: `${type}:${fundId}`.
  // user-scoped types still namespace by fundId (the "primary fund"
  // the activity was logged against) so the snooze record has a
  // canonical home.
  id: string;
  type: ActionItemType;
  fundId: string;
  // Display label for the fund, so the card can say "Bob's Fund"
  // without the client doing a second lookup.
  fundLabel: string;
  title: string;
  description: string;
  // Primary CTA text + the route to take when tapped. Routes are
  // relative paths (e.g. "/activate", "/settings?bank=1"). The
  // client opens these via wouter setLocation.
  ctaLabel: string;
  ctaPath: string;
  // When non-null, this item is currently snoozed and should be
  // hidden from the bell count + the visible action queue until
  // `now > snoozedUntil`. Server filters out snoozed items by
  // default; the field is only present for diagnostic / "show
  // snoozed too" UI variants.
  snoozedUntil: string | null;
  canSnooze: boolean;
  category: ActionItemCategory;
  // Severity drives the visual register on the client (gold tint
  // for blocking vs amber for advisory). NOT a count of urgency —
  // blocking means "the thing this gate guards is unavailable
  // right now without this fix."
  severity: "blocking" | "advisory";
}

// Default snooze duration when the user picks "Remind tomorrow"
// without explicitly specifying a later time. 24 hours, locked per
// the user-confirmed direction.
export const DEFAULT_SNOOZE_HOURS = 24;

// Items that should NEVER be snoozable — typically blocking-decision
// items where deferring would leave money in limbo. Large-gift holds
// fall here because Stripe wants a decision; sitting on them rolls
// into an automatic action eventually.
export const NON_SNOOZABLE_TYPES: readonly ActionItemType[] = [
  "large_gift_hold_started",
];

export function isSnoozable(type: ActionItemType): boolean {
  return !NON_SNOOZABLE_TYPES.includes(type);
}
